### PR TITLE
Feature/52-lombok

### LINKED ISSUE #52: Add Project Lombok and Refactor

### PR DESCRIPTION
**Pull request by mslowiak**
Fixes: #52

Unblocks: #13

### CODE REVIEW

**Comment by mslowiak** [comment]
@Himovic It is done, take a look on it in your free time :)

**Comment by Himovic** [comment]
@mslowiak Thank you so much :). I will look on it and if i don't understand anything i'll come to you because i'am new on Lombok and i want to learn it.

**Comment by mslowiak** [comment]
**How to setup Lombok in Intelij?**

1. Download lombok plugin. Settings -> Plugins -> Search for 'Lombok'
2. Settings -> Other Settings -> Enable Lombok
3. Settings -> Build, Execution, Deployment -> Compiler -> Annotation Processors -> Enable annotaion processing

**Comment by mslowiak** [comment]
Is there any other issue that I can help you with?

**Comment by Himovic** [comment]
Yeah ! My actuel project contains 2 profils, one for default and other profil for springdatajpa. When i run the project with springdatajpa profile, an error occurs saying that i need to define a bean of type OwnerRepository. But OwnerRepository is an interface that implement CrudRepository so we don't need to define a class implementation for that. I tried @Repository, @Service, @Component but nothing works.

**Comment by mslowiak** [comment]
@Himovic Could you create issue with that?
When I run application with 'springdatajpa' profile I have output:

> Parameter 0 of constructor in org.pet.clinic.data.Services.Map.OwnerServiceMap required a single bean, but 2 were found:
	- petServiceMap: defined in file [F:\PROGRAMOWANIE\open source\sfg-clinic-pet\pet-clinic-data\target\classes\org\pet\clinic\data\Services\Map\PetServiceMap.class]
	- petSpringDataJpaService: defined in file [F:\PROGRAMOWANIE\open source\sfg-clinic-pet\pet-clinic-data\target\classes\org\pet\clinic\data\Services\SpringDataJpa\PetSpringDataJpaService.class]

So it is about `OwnerServiceMap`

**Comment by Himovic** [comment]
@mslowiak i create an issue for that. #61

**Comment by Himovic** [comment]
I'am thinking that i need to create a class impl for each repository and implement the CRUD methods because i used H2 Database for springdatajpa profile and HashMap for servicemap profile. What do you think ?

**Pull request closed without merging**
